#!/bin/bash

cd /proc
procs=$( echo [0-9]* )

for p in ${procs[*]}; do
    pushd $p >/dev/null
    cmd=$(tr '\0' ' ' < cmdline)
    if [[ "${cmd}" == *last* ]]; then
        echo ${p}: ${cmd}
    fi
    popd >/dev/null
done