#!/bin/bash

cd /proc
readarray procs <<< $( echo [0-9]* | tr ' ' '\n' | sort -n )

for p in ${procs[*]}; do
    pushd $p >/dev/null
    cmd=$(tr '\0' ' ' < cmdline)
    if [[ "${cmd}" == *last* ]]; then
        echo ${p}: ${cmd}
    fi
    popd >/dev/null
done