#!/bin/bash

function search() {
    local what="${1}"
    local -a procs

    cd /proc
    readarray procs <<< $( echo [0-9]* | tr ' ' '\n' | sort -n )

    for p in ${procs[*]}; do
        if [ ! -d ${p} ]; then
            continue
        fi
        pushd $p >/dev/null
        cmd=$(tr '\0' ' ' < cmdline)
        if [[ "${cmd}" == *${what}* ]]; then
            echo ${p}: ${cmd}
        fi
        popd >/dev/null
    done
}

# check we've been given one argument
if (( $# != 1 )); then
    usage
    exit 1
fi

search ${1}
