#!/bin/bash

function search() {
    local what="${1}"

    cd /proc
    procs=$( echo [0-9]* )

    for p in ${procs[*]}; do
        if [ ! -d ${p} ]; then
            continue
        fi
        pushd $p >/dev/null
        cmd=$(tr '\0' ' ' < cmdline)
        if [[ "${cmd}" == *last* ]]; then
            echo ${p}: ${cmd}
        fi
        popd >/dev/null
    done
}

# check we've been given one argument
if (( $# != 1 )); then
    usage
    exit 1
fi

search ${1}
